FROM python:3.9

WORKDIR /app

# Install poetry
RUN pip install poetry

# Copy poetry files
COPY pyproject.toml poetry.lock* /app/

# Install dependencies
RUN poetry config virtualenvs.create false \
  && poetry install --no-root

# Copy the rest of your application's code
COPY . /app

# Expose the port the app runs on
EXPOSE 5000

# Run the application with Gunicorn
CMD ["poetry", "run", "gunicorn", "--bind", "0.0.0.0:5000", "app.main:app"]