version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=ratestask
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=ratestask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.flask
    command: poetry run pytest
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=ratestask
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: